version: "3.8"

services:
  react-app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "yarn install && yarn start"
